[package]
name = "contracts"
version = "0.2.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.4"
openzeppelin_access = "1.0.0"
openzeppelin_token = "1.0.0"

[dev-dependencies]
openzeppelin_utils = "1.0.0"
snforge_std = "0.38.2"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "MAINNET_LATEST"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_8"
block_id.tag = "latest"